# aistm-project/nginx/default.conf

server {
    listen 80;
    server_name localhost;
    root /var/www/html/public; # Laravelのpublicディレクトリをルートに指定

    index index.php index.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # backendコンテナの9000ポートにリクエストを転送
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # その他、Laravelに必要な設定...
    location ~ /\.ht {
        deny all;
    }
}